package com.letscode.mvcGuide.controller;

import com.letscode.mvcGuide.domain.Message;
import com.letscode.mvcGuide.domain.User;
import com.letscode.mvcGuide.repos.MessageRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.UUID;

@Controller // This means that this class is a Controller
public class MainController {

    @Value("${upload.path}")  // get uploadPath from properties file and put it into variable
    private String uploadPath;

    @GetMapping("/") // This means URL's start with /greeting (after Application path)
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepo messageRepo;

    @GetMapping("/main")
    public String main(@RequestParam(required = false, defaultValue = "") String filter, Model model) {
        Iterable<Message> messages = messageRepo.findAll();

        if (filter != null && !filter.isEmpty()) {
            messages = messageRepo.findByTag(filter);
        } else {
            messages = messageRepo.findAll();
        }

        model.addAttribute("messages", messages);
        model.addAttribute("filter", filter);
        return "main";
    }

    // @RequestParam means it is a parameter from the GET or POST request
    @PostMapping("/main")
    public String add(
            @AuthenticationPrincipal User user,
            @RequestParam String text,
            @RequestParam String tag,
            Map<String, Object> model,
            @RequestParam("file") MultipartFile file
    ) throws IOException {
        Message message = new Message(text, tag, user); // create message object

        if (file != null && !file.getOriginalFilename().isEmpty()) {
            File uploadDir = new File(uploadPath);

            if (!uploadDir.exists()){  // create dir if it doesn`t exist
                uploadDir.mkdir();
            }

            String uuidFile = UUID.randomUUID().toString(); // create unique id for file
            String resultFileName = uuidFile + "." + file.getOriginalFilename();
            // upload file
            file.transferTo(new File(uploadPath + "/" + resultFileName));
            message.setFilename(resultFileName);
        }

        messageRepo.save(message); // save to db

        //return list of messages
        Iterable<Message> messages = messageRepo.findAll();
        model.put("messages", messages);
        return "main";
    }

}
